import { ConstellationData, Direction } from '../types';

// In a real backend scenario, these would be paths to local assets like '/images/beasts/jiao.png'
// Here we use deterministic URLs that act as our "stored" assets.
const getStaticAssetUrl = (animal: string, element: string, seed: number) => {
  // Updated Prompt: 3D, C4D, Pop Mart Style, Guochao, Festive
  const prompt = `cute 3D chinese mythical beast ${animal} representing ${element} element, pop mart style, blind box toy design, C4D, octane render, clay texture, vibrant colors, glowing accessories, festive atmosphere, clean dark blue background, masterpiece, 8k`;
  const encoded = encodeURIComponent(prompt);
  return `https://image.pollinations.ai/prompt/${encoded}?width=800&height=800&seed=${seed}&nologo=true`;
};

// The "Backend" Database
export const CONSTELLATIONS: ConstellationData[] = [
  // --- EAST (Azure Dragon) ---
  {
    id: 0,
    name: '角',
    fullName: '角木蛟',
    animal: '蛟',
    element: '木',
    direction: Direction.EAST,
    description: '角星造作主荣昌，外进田财及女郎。嫁娶婚姻出贵子，文人及第见君王。',
    poem: '东方苍龙之角，为万物生发之首。',
    fortune: '角宿为二十八星宿之首，象征着春回大地，万物复苏。你天生具有领导潜质与开创精神，正如破土而出的新芽。近期运势如日中天，适合开启新的计划或学习新的技能，但需注意戒骄戒躁，稳扎稳打方能长久。',
    imageUrl: getStaticAssetUrl('Flood Dragon', 'Wood', 100),
  },
  {
    id: 1,
    name: '亢',
    fullName: '亢金龙',
    animal: '龙',
    element: '金',
    direction: Direction.EAST,
    description: '亢星造作长房当，十日之中主有殃。田地消磨官失职，投军定是虎狼伤。',
    poem: '刚毅正直，如龙之升天。',
    fortune: '亢宿象征着极度的刚强与正直。你性格中有着不屈不挠的韧性，遇强则强。然而“亢龙有悔”，在人际交往中建议多一份柔和与包容，刚柔并济方能化解阻力，成就大业。',
    imageUrl: getStaticAssetUrl('Majestic Dragon', 'Metal', 101),
  },
  {
    id: 2,
    name: '氐',
    fullName: '氐土貉',
    animal: '貉',
    element: '土',
    direction: Direction.EAST,
    description: '氐星造作主灾凶，费尽田园仓库空。埋葬不可用此日，悬绳吊颈祸重重。',
    poem: '根基深厚，然需防口舌。',
    fortune: '氐宿代表着根基与根本。你为人稳重，做事有条不紊，是团队中不可或缺的基石。近期需注意防范口舌是非，少说多做，默默耕耘自有收获，切勿卷入无谓的争端。',
    imageUrl: getStaticAssetUrl('Raccoon Dog Beast', 'Earth', 102),
  },
  {
    id: 3,
    name: '房',
    fullName: '房日兔',
    animal: '兔',
    element: '日',
    direction: Direction.EAST,
    description: '房星造作田园进，血财牛马遍山岗。更招外处客留住，良妻美妾秀满堂。',
    poem: '吉庆之星，多福多寿。',
    fortune: '房宿是著名的吉星，象征着富足与安乐。你通常运气不错，能在关键时刻得到贵人相助。生性乐观，无论顺境逆境都能保持平和心态。珍惜当下的福分，多行善事，福气自会绵延。',
    imageUrl: getStaticAssetUrl('Jade Rabbit', 'Sun', 103),
  },
  {
    id: 4,
    name: '心',
    fullName: '心月狐',
    animal: '狐',
    element: '月',
    direction: Direction.EAST,
    description: '心星造作大为凶，更遭刑讼狱囚中。忤逆官非因此起，兄弟姐妹有刑伤。',
    poem: '心思缜密，然易招猜忌。',
    fortune: '心宿位于苍龙心脏，象征着智慧与核心。你心思细腻，洞察力极强，往往能看透事物的本质。但有时过于敏感多疑，容易让自己陷入内耗。学会信任与放手，你的才华将得到更充分的施展。',
    imageUrl: getStaticAssetUrl('Nine-Tailed Fox', 'Moon', 104),
  },
  {
    id: 5,
    name: '尾',
    fullName: '尾火虎',
    animal: '虎',
    element: '火',
    direction: Direction.EAST,
    description: '尾星造作主天恩，富贵荣华福寿增。招财进宝与田宅，和合婚姻贵子孙。',
    poem: '勇猛精进，无往不利。',
    fortune: '尾宿代表着苍龙之尾，虽在后却有力。你性格中有好胜的一面，且具备极强的爆发力。在事业上往往能后来居上，获得令人瞩目的成就。保持这份冲劲，成功就在不远处。',
    imageUrl: getStaticAssetUrl('Divine Tiger', 'Fire', 105),
  },
  {
    id: 6,
    name: '箕',
    fullName: '箕水豹',
    animal: '豹',
    element: '水',
    direction: Direction.EAST,
    description: '箕星造作主高强，岁岁年年大吉昌。埋葬修坟大吉利，田蚕牛马遍山岗。',
    poem: '风起云涌，好辩多才。',
    fortune: '箕宿好风，象征着自由与变动。你口才极佳，善于交际，喜欢新鲜事物，不喜欢受拘束。你的生活中充满了变化与机遇，抓住风口，你就能乘风而起，创造属于自己的天地。',
    imageUrl: getStaticAssetUrl('Water Leopard', 'Water', 106),
  },

  // --- NORTH (Black Tortoise) ---
  {
    id: 7,
    name: '斗',
    fullName: '斗木獬',
    animal: '獬',
    element: '木',
    direction: Direction.NORTH,
    description: '斗星造作主招财，文武官员位鼎台。田宅家财千万进，坟茔修筑富贵来。',
    poem: '天之府库，量才录用。',
    fortune: '斗宿被称为“天庙”，象征着崇高的地位与才华。你自尊心强，有着远大的志向。在工作中往往能独当一面。近期利于考取功名或职位晋升，是展现才华的好时机。',
    imageUrl: getStaticAssetUrl('Xiezhi Unicorn', 'Wood', 107),
  },
  {
    id: 8,
    name: '牛',
    fullName: '牛金牛',
    animal: '牛',
    element: '金',
    direction: Direction.NORTH,
    description: '牛星造作主灾危，九横三灾不可推。家宅不安人口退，田蚕不利主人衰。',
    poem: '勤恳劳作，大器晚成。',
    fortune: '牛宿象征着牺牲与奉献。你性格坚韧，能够吃苦耐劳，不轻言放弃。虽然早年可能较为辛苦，但属于大器晚成之相。只需坚持不懈，终将苦尽甘来，收获丰硕的果实。',
    imageUrl: getStaticAssetUrl('Iron Ox', 'Metal', 108),
  },
  {
    id: 9,
    name: '女',
    fullName: '女土蝠',
    animal: '蝠',
    element: '土',
    direction: Direction.NORTH,
    description: '女星造作损婆娘，兄弟相嫌似虎狼。埋葬生灾逢鬼怪，颠邪疾病主瘟惶。',
    poem: '心灵手巧，独具匠心。',
    fortune: '女宿代表着手工与技艺。你内心丰富，或许外表沉静，但内心世界斑斓。适合从事需要专注力与创造力的工作。近期注意调节情绪，多参与社交活动，避免过度封闭。',
    imageUrl: getStaticAssetUrl('Giant Bat', 'Earth', 109),
  },
  {
    id: 10,
    name: '虚',
    fullName: '虚日鼠',
    animal: '鼠',
    element: '日',
    direction: Direction.NORTH,
    description: '虚星造作主卓灾，男女孤眠不唱乖。内乱风声无礼节，儿孙媳妇伴墙开。',
    poem: '虽有波折，终能积聚。',
    fortune: '虚宿象征着空虚与充盈的辩证。你人生可能经历过一些起伏，但这些经历都是宝贵的财富。你有着极强的适应能力，能在逆境中寻找生机，未来必将由虚转实，富贵盈门。',
    imageUrl: getStaticAssetUrl('Mystical Rat', 'Sun', 110),
  },
  {
    id: 11,
    name: '危',
    fullName: '危月燕',
    animal: '燕',
    element: '月',
    direction: Direction.NORTH,
    description: '危星造作主天赫，此号通天第一峰。埋葬修坟大吉利，一门荣贵福无穷。',
    poem: '居安思危，敏捷灵巧。',
    fortune: '危宿代表着高度与险峻。你性格独立，喜欢挑战，不甘平庸。行事风格雷厉风行，但也容易冲动。建议凡事三思而后行，“居安思危”是你的人生箴言，稳中求进方为上策。',
    imageUrl: getStaticAssetUrl('Swallow Bird', 'Moon', 111),
  },
  {
    id: 12,
    name: '室',
    fullName: '室火猪',
    animal: '猪',
    element: '火',
    direction: Direction.NORTH,
    description: '室星造作进田牛，儿孙代代近王侯。富贵荣华天上至，寿如彭祖八千秋。',
    poem: '刚毅果决，勇往直前。',
    fortune: '室宿象征着营室与家业。你性格豪爽，讲义气，人缘极好。有着天生的管理才能与财富运。只要愿意付出努力，定能家业兴旺，富甲一方。是值得信赖的合作伙伴。',
    imageUrl: getStaticAssetUrl('Wild Boar', 'Fire', 112),
  },
  {
    id: 13,
    name: '壁',
    fullName: '壁水貐',
    animal: '貐',
    element: '水',
    direction: Direction.NORTH,
    description: '壁星造作主增财，丝蚕大熟福滔天。奴婢自来人口进，一门荣显尽绵绵。',
    poem: '文章华国，好学不倦。',
    fortune: '壁宿代表着墙壁与图书。你性格内敛，喜爱读书与思考，有着深厚的文化底蕴。你是默默的支持者与建设者，虽然不爱张扬，但你的贡献有目共睹。利于从事学术或幕后工作。',
    imageUrl: getStaticAssetUrl('Porcupine Beast', 'Water', 113),
  },

  // --- WEST (White Tiger) ---
  {
    id: 14,
    name: '奎',
    fullName: '奎木狼',
    animal: '狼',
    element: '木',
    direction: Direction.WEST,
    description: '奎星造作得祯祥，家内荣和大吉昌。若是埋葬阴卒死，当年定主两三伤。',
    poem: '文运昌盛，才华横溢。',
    fortune: '奎宿被视为“文曲星”之一，主文章考运。你才华横溢，思维敏捷，可能有很好的艺术或文学天赋。在群体中容易脱颖而出，但要注意不要恃才傲物，保持谦逊能让你走得更远。',
    imageUrl: getStaticAssetUrl('White Wolf', 'Wood', 114),
  },
  {
    id: 15,
    name: '娄',
    fullName: '娄金狗',
    animal: '狗',
    element: '金',
    direction: Direction.WEST,
    description: '娄星造作起田庭，安宫竖柱利门庭。门前井水兼沟壑，人丁牛马增前程。',
    poem: '忠诚坚守，兴家立业。',
    fortune: '娄宿象征着聚众与兴旺。你为人忠诚可靠，责任心强，是值得托付重任的人。你有很好的理财观念与持家能力，生活会随着时间的推移越来越富足安稳。',
    imageUrl: getStaticAssetUrl('Golden Dog', 'Metal', 115),
  },
  {
    id: 16,
    name: '胃',
    fullName: '胃土彘',
    animal: '彘',
    element: '土',
    direction: Direction.WEST,
    description: '胃星造作事如何，富贵荣华喜气多。埋葬贵临官禄位，夫妇齐眉老少和。',
    poem: '性情刚烈，福寿双全。',
    fortune: '胃宿代表着胃口与仓廪。你性格直爽，甚至有些急躁刚烈，但心地善良。你的一生福禄不缺，身体健康。只要能控制好脾气，处理好人际关系，人生将非常圆满。',
    imageUrl: getStaticAssetUrl('Pheasant Beast', 'Earth', 116),
  },
  {
    id: 17,
    name: '昴',
    fullName: '昴日鸡',
    animal: '鸡',
    element: '日',
    direction: Direction.WEST,
    description: '昴星造作进田牛，埋葬官灾不得休。重丧二日三人死，卖尽田园不记丘。',
    poem: '名扬四海，威震八方。',
    fortune: '昴宿即著名的“七姊妹星团”，光芒耀眼。你可能在某个领域拥有特殊的才能或名望。你言语犀利，有说服力。注意避免卷入官非或不必要的争执，用你的才华去照亮他人。',
    imageUrl: getStaticAssetUrl('Divine Rooster', 'Sun', 117),
  },
  {
    id: 18,
    name: '毕',
    fullName: '毕月乌',
    animal: '乌',
    element: '月',
    direction: Direction.WEST,
    description: '毕星造作主光前，买得田园有粟钱。埋葬此日添官职，田蚕大熟永丰年。',
    poem: '持之以恒，大器晚成。',
    fortune: '毕宿象征着网罗与狩猎。你做事有计划，有耐心，目标明确。不像他人追求速成，你懂得“放长线钓大鱼”。坚持你的信念，你的收获将是巨大的且长久的。',
    imageUrl: getStaticAssetUrl('Three-legged Crow', 'Moon', 118),
  },
  {
    id: 19,
    name: '觜',
    fullName: '觜火猴',
    animal: '猴',
    element: '火',
    direction: Direction.WEST,
    description: '觜星造作有徒刑，三年必定主伶丁。埋葬卒死多因此，取定寅年使杀人。',
    poem: '机智灵活，能言善辩。',
    fortune: '觜宿虽然极小，但能量集中。你极其聪明，反应快，口才好，善于经商或谈判。但有时过于精明会让人产生距离感。学会“难得糊涂”，以诚待人，会让你的路越走越宽。',
    imageUrl: getStaticAssetUrl('Monkey King', 'Fire', 119),
  },
  {
    id: 20,
    name: '参',
    fullName: '参水猿',
    animal: '猿',
    element: '水',
    direction: Direction.WEST,
    description: '参星造作旺人家，文星照耀大光华。只因造作田财旺，埋葬招灾男女花。',
    poem: '才思敏捷，文武双全。',
    fortune: '参宿是西方的将军星，光芒璀璨。你才华出众，甚至带有一点叛逆与傲气。你具备改革创新的精神，不畏权贵。在动荡或变革的环境中，最能体现你的价值。',
    imageUrl: getStaticAssetUrl('White Ape', 'Water', 120),
  },

  // --- SOUTH (Vermilion Bird) ---
  {
    id: 21,
    name: '井',
    fullName: '井木犴',
    animal: '犴',
    element: '木',
    direction: Direction.SOUTH,
    description: '井星造作旺蚕田，金榜题名第一先。埋葬须防惊卒死，狂颠风疾入黄泉。',
    poem: '深谋远虑，井井有条。',
    fortune: '井宿象征着水井与法度。你做事极有条理，讲究规矩，公正无私。你像一口深井，内涵丰富却不轻易外露。适合从事法律、行政或管理类工作，稳健是你的代名词。',
    imageUrl: getStaticAssetUrl('Wild Dog Tapir', 'Wood', 121),
  },
  {
    id: 22,
    name: '鬼',
    fullName: '鬼金羊',
    animal: '羊',
    element: '金',
    direction: Direction.SOUTH,
    description: '鬼星起造卒人亡，堂前不见主人郎。埋葬此日官禄至，儿孙代代近君王。',
    poem: '奇特诡谲，出奇制胜。',
    fortune: '鬼宿虽名鬼，实为“舆鬼”，主财富与奇异。你的直觉惊人，常常能感知到他人忽略的细节。财运极佳，偏财运旺盛。性格中带有神秘色彩，不按常理出牌往往能获得奇效。',
    imageUrl: getStaticAssetUrl('Golden Sheep', 'Metal', 122),
  },
  {
    id: 23,
    name: '柳',
    fullName: '柳土獐',
    animal: '獐',
    element: '土',
    direction: Direction.SOUTH,
    description: '柳星造作主遭官，昼夜偷闲不暂安。埋葬瘟惶多疾病，田园退尽守孤寒。',
    poem: '柔韧多变，心思深沉。',
    fortune: '柳宿象征着柳条的柔顺与坚韧。你性格看似温和，实则内心很有主见，甚至有些固执。你善于以柔克刚，适应能力极强。注意不要过于沉迷于心计，真诚是打动人心的钥匙。',
    imageUrl: getStaticAssetUrl('Roe Deer', 'Earth', 123),
  },
  {
    id: 24,
    name: '星',
    fullName: '星日马',
    animal: '马',
    element: '日',
    direction: Direction.SOUTH,
    description: '星星造作主妖灵，家内厨庭犬吠声。生财进益皆无用，总然归却一风尘。',
    poem: '奔腾万里，志在四方。',
    fortune: '星宿代表着急促与光明。你性急如火，做事效率高，不喜欢拖泥带水。你像一匹奔腾的骏马，渴望广阔的天地。年轻时可能较为奔波，但晚年定能享清福。',
    imageUrl: getStaticAssetUrl('Sun Horse', 'Sun', 124),
  },
  {
    id: 25,
    name: '张',
    fullName: '张月鹿',
    animal: '鹿',
    element: '月',
    direction: Direction.SOUTH,
    description: '张星造作主吉祥，一庭金玉积满堂。埋葬并修官禄进，妻贤子贵寿绵长。',
    poem: '温文尔雅，祥和富贵。',
    fortune: '张宿象征着张开的网或琴弦。你气质优雅，待人接物恰到好处，人缘极佳。你的一生多平和安详，少有大起大落。由于得体的举止，常能获得长辈或上司的青睐。',
    imageUrl: getStaticAssetUrl('Moon Deer', 'Moon', 125),
  },
  {
    id: 26,
    name: '翼',
    fullName: '翼火蛇',
    animal: '蛇',
    element: '火',
    direction: Direction.SOUTH,
    description: '翼星造作主天孤，岁岁年年烧屋庐。埋葬修坟也如此，家门孤寡守空虚。',
    poem: '飞翔九天，才艺双绝。',
    fortune: '翼宿象征着朱雀的翅膀，主飞翔与音乐。你热爱艺术，崇尚自由，不喜欢被世俗的条条框框所束缚。你可能需要在外地发展才能更好地施展才华，远方有你的梦想。',
    imageUrl: getStaticAssetUrl('Winged Serpent', 'Fire', 126),
  },
  {
    id: 27,
    name: '轸',
    fullName: '轸水蚓',
    animal: '蚓',
    element: '水',
    direction: Direction.SOUTH,
    description: '轸星造作主增财，风水高官位鼎台。田宅家财千万进，坟茔修筑富贵来。',
    poem: '能屈能伸，顺势而为。',
    fortune: '轸宿位于朱雀之尾，象征着结束与再生。你心思缜密，行动敏捷，非常善于观察风色。你有着极强的生命力与恢复力，无论遇到什么困难，都能像蚯蚓松土一般，默默耕耘，最终换来生机。',
    imageUrl: getStaticAssetUrl('Dragon Earthworm', 'Water', 127),
  },
];

export const getConstellationByIndex = (index: number): ConstellationData => {
  // Ensure circular safety
  const safeIndex = ((index % 28) + 28) % 28;
  return CONSTELLATIONS[safeIndex];
}